---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: capstone-app
  labels:
    app: capstone-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone-app
  template:
    metadata:
      labels:
        app: capstone-app
    spec:
      containers:
      - name: capstone-app
        image: aobri/cloud-devops-capstone:latest
        imagePullPolicy: Always
        ports:
        - name: http-port
          containerPort: 80
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
