---
kind: Service
apiVersion: v1
metadata:
  name: capstone-app
  labels:
    app: capstone-app
spec:
  ports:
  - port: 8080
    targetPort: 80
  selector:
    app: capstone-app
  type: LoadBalancer
